In [1]:
import tensorflow as tf

In [11]:
#Create a dataset with values from 0 to 9
ds = tf.data.Dataset.range(10)

for i in ds:
  print(i.numpy())

0
1
2
3
4
5
6
7
8
9

In [12]:
ds = tf.data.Dataset.range(10)
#Create a window of size 5. Each window has a max of 5 elements and will increase the numbers by 1 (Since shift = 1)
ds = ds.window(5,shift=1)
for window in ds:
  for val in window:
    print(val.numpy(), end=' ')
  print()

0 1 2 3 4
1 2 3 4 5
2 3 4 5 6
3 4 5 6 7
4 5 6 7 8
5 6 7 8 9
6 7 8 9
7 8 9
8 9
9

In [13]:
ds = tf.data.Dataset.range(10)
#Drop_remainder so windows will be dropped if its size is less than 5
ds = ds.window(5,shift=1, drop_remainder=True)
for window in ds:
  for val in window:
    print(val.numpy(), end=' ')
  print()

0 1 2 3 4
1 2 3 4 5
2 3 4 5 6
3 4 5 6 7
4 5 6 7 8
5 6 7 8 9

In [14]:
ds = tf.data.Dataset.range(10)
ds = ds.window(5,shift=1, drop_remainder=True)
#Write a function that flattens the ds and batches it into groups of 5 (So you can see it as arrays containing 5 elements each)
#You use flat_map to ensure the order of data is the same. It flattens all elements so the ds will be a 1D array
ds = ds.flat_map(lambda window:window.batch(5))
for window in ds:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]

In [15]:
ds = tf.data.Dataset.range(10)
ds = ds.window(5,shift=1, drop_remainder=True)
ds = ds.flat_map(lambda window:window.batch(5))
#Create a function that takes the data and returns 2 sets of values (one for X and one for Y)
ds = ds.map(lambda data: (data[:-1], data[-1:]))
for x,y in ds:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]

In [16]:
ds = tf.data.Dataset.range(10)
ds = ds.window(5,shift=1, drop_remainder=True)
ds = ds.flat_map(lambda window:window.batch(5))
ds = ds.map(lambda data: (data[:-1], data[-1:]))
#Shuffle the dataset using buffer size of 10
ds = ds.shuffle(buffer_size = 10)
for x,y in ds:
  print(x.numpy(), y.numpy())

[5 6 7 8] [9]
[3 4 5 6] [7]
[4 5 6 7] [8]
[0 1 2 3] [4]
[2 3 4 5] [6]
[1 2 3 4] [5]

In [17]:
ds = tf.data.Dataset.range(10)
ds = ds.window(5,shift=1, drop_remainder=True)
ds = ds.flat_map(lambda window:window.batch(5))
ds = ds.map(lambda data: (data[:-1], data[-1:]))
ds = ds.shuffle(buffer_size = 10)
#Batch the dataset into batches of 2 (One batch will have 2 Xs and the 2 corresponding Ys)
ds = ds.batch(2).prefetch(1)
for x,y in ds:
  print(x.numpy(), y.numpy())

[[4 5 6 7]
 [2 3 4 5]] [[8]
 [6]]
[[3 4 5 6]
 [5 6 7 8]] [[7]
 [9]]
[[1 2 3 4]
 [0 1 2 3]] [[5]
 [4]]

In [18]:
series = [20.7, 17.9, 18.8, 14.6, 15.8, 15.8, 15.8, 17.4, 21.8, 20.]

In [19]:
new = tf.expand_dims(series, axis=-1)
ds = tf.data.Dataset.from_tensor_slices(new)
for i in ds:
  print(i.numpy())

[20.7]
[17.9]
[18.8]
[14.6]
[15.8]
[15.8]
[15.8]
[17.4]
[21.8]
[20.]

In [20]:
ds = tf.data.Dataset.from_tensor_slices(new)
ds = ds.window(5, shift=1, drop_remainder=True)
ds = ds.flat_map(lambda window:window.batch(5))
for window in ds:
  print(window.numpy())

[[20.7]
 [17.9]
 [18.8]
 [14.6]
 [15.8]]
[[17.9]
 [18.8]
 [14.6]
 [15.8]
 [15.8]]
[[18.8]
 [14.6]
 [15.8]
 [15.8]
 [15.8]]
[[14.6]
 [15.8]
 [15.8]
 [15.8]
 [17.4]]
[[15.8]
 [15.8]
 [15.8]
 [17.4]
 [21.8]]
[[15.8]
 [15.8]
 [17.4]
 [21.8]
 [20. ]]

In [21]:
new = tf.expand_dims(series, axis=-1)
ds = tf.data.Dataset.from_tensor_slices(new)
ds = ds.window(5, shift=1, drop_remainder=True)
ds = ds.flat_map(lambda window:window.batch(5))
ds = ds.map(lambda x: (x[:-1], x[-1:]))
ds = ds.batch(3).prefetch(1)
for x in ds:
  print(x)
  print()

(<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[20.7],
        [17.9],
        [18.8],
        [14.6]],

       [[17.9],
        [18.8],
        [14.6],
        [15.8]],

       [[18.8],
        [14.6],
        [15.8],
        [15.8]]], dtype=float32)>, <tf.Tensor: shape=(3, 1, 1), dtype=float32, numpy=
array([[[15.8]],

       [[15.8]],

       [[15.8]]], dtype=float32)>)

(<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[14.6],
        [15.8],
        [15.8],
        [15.8]],

       [[15.8],
        [15.8],
        [15.8],
        [17.4]],

       [[15.8],
        [15.8],
        [17.4],
        [21.8]]], dtype=float32)>, <tf.Tensor: shape=(3, 1, 1), dtype=float32, numpy=
array([[[17.4]],

       [[21.8]],

       [[20. ]]], dtype=float32)>)